---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo-deploy
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: kustomize
  url: https://github.com/steveww/podinfo-deploy.git

