apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: backend
spec:
  # rollback if not finished in time
  progressDeadlineSeconds: 300
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  service:
    port: 9898
  analysis:
    interval: 1m
    threshold: 3
    maxWeight: 30
    stepWeight: 10
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        # P99 request time (ms)
        max: 250
      interval: 1m
    webhooks:
    - name: load-test
      type: rollout
      url: http://flagger-loadtest-loadtester.loadtest/
      metadata:
        cmd: "sleep 10; hey -z 1m -q 10 -c 2 http://backend-canary.podinfo:9898/"
    - name: events
      type: event
      url: http://webhook.default/webhook
      metadata:
        app: backend
