apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend
spec:
  # rollback if not finished in time
  progressDeadlineSeconds: 300
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  service:
    port: 9898
  analysis:
    interval: 30s
    threshold: 3
    maxWeight: 50
    stepWeight: 5
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 10s
    - name: request-duration
      thresholdRange:
        # P99 request time (ms)
        max: 250
      interval: 10s
