apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend
spec:
  # rollback if not finished in time
  progressDeadlineSeconds: 300
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  service:
    port: 9898
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 5
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 10s
    - name: request-duration
      thresholdRange:
        # P99 request time (ms)
        max: 250
      interval: 10s
    webhooks:
    - name: load-test
      type: rollout
      url: http://loadtester.loadtest/
      metadata:
        cmd: "hey -z 30s -q 4 -c 2 http://frontend-canary.podinfo:9898/"
    - name: events
      type: event
      url: http://webhook.default/webhook
      metadata:
        app: frontend