apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend
spec:
  # rollback if not finished in time
  progressDeadlineSeconds: 300
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  service:
    port: 9898
  analysis:
    # How often the canary is evaluated
    interval: 1m
    threshold: 3
    maxWeight: 50
    stepWeight: 10
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      # duration for metric query
      interval: 1m
    - name: request-duration
      thresholdRange:
        # P99 request time (ms)
        max: 250
      # duration for metric query
      interval: 1m
    webhooks:
    - name: load-test
      type: rollout
      url: http://flagger-loadtester.loadgen/
      metadata:
        cmd: "hey -z 1m -q 10 -c 2 http://frontend-canary.podinfo:9898/"
    - name: events
      type: event
      url: http://webhook.default/webhook
      metadata:
        app: frontend
