---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-staging
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo-staging
  validation: client

