---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: wego-3e6f3231bdf972c5992f3e1d5720d691
  name: podinfo-deploy
  namespace: wego-system
spec:
  deployment_type: kustomize
  path: ./
  url: ssh://git@github.com/paulcarlton-ww/podinfo-deploy.git
