---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-54f3050fdca9cc6267395ca640fd738d
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: kustomize
  deployment_type: kustomize
  path: staging
  source_type: git
  url: ssh://git@github.com/steveww/podinfo-deploy.git
